### PR TITLE
Updated README.md-2

### PR DESCRIPTION
**Pull request by mrahul27devops**
Updating Read.MD file to demo git pull with reviewer approval process

### CODE REVIEW

**Comment by mrahul27** [comment]
why do u need a pull here

**Comment by mrahul27devops** [comment]
this is a demo pull for reviewer approval

**Comment by mrahul27** [comment]
ok np

**Comment by mrahul27devops** [comment]
is it ok

**Review by mrahul27 — APPROVED** [review]
all right approved

**Pull request closed without merging**
